// ==========================================
// MALE QUESTIONS DATABASE - EXPANDED
// ==========================================

export const maleQuestions = [
  // ===== ANIME =====
  { q: { en: 'Who is the main character in Naruto?', fr: 'Qui est le personnage principal de Naruto?', ar: 'من هو الشخصية الرئيسية في ناروتو؟' }, opts: { en: ['Sasuke', 'Kakashi', 'Naruto Uzumaki', 'Sakura'], fr: ['Sasuke', 'Kakashi', 'Naruto Uzumaki', 'Sakura'], ar: ['ساسكي', 'كاكاشي', 'ناروتو أوزوماكي', 'ساكورا'] }, correct: 2, category: { en: 'Anime', fr: 'Anime', ar: 'أنمي' } },
  { q: { en: 'Which anime has "Sharingan"?', fr: 'Quel anime a "Sharingan"?', ar: 'أي أنمي يحتوي على "الشارينغان"؟' }, opts: { en: ['Bleach', 'Naruto', 'One Piece', 'Dragon Ball'], fr: ['Bleach', 'Naruto', 'One Piece', 'Dragon Ball'], ar: ['بليتش', 'ناروتو', 'ون بيس', 'دراغون بول'] }, correct: 1, category: { en: 'Anime', fr: 'Anime', ar: 'أنمي' } },
  { q: { en: 'Luffy\'s power in One Piece?', fr: 'Le pouvoir de Luffy dans One Piece?', ar: 'قوة لوفي في ون بيس؟' }, opts: { en: ['Fire', 'Rubber', 'Ice', 'Lightning'], fr: ['Feu', 'Caoutchouc', 'Glace', 'Foudre'], ar: ['نار', 'مطاط', 'ثلج', 'برق'] }, correct: 1, category: { en: 'Anime', fr: 'Anime', ar: 'أنمي' } },
  { q: { en: 'What is the name of Goku\'s signature attack?', fr: 'Quel est le nom de l\'attaque signature de Goku?', ar: 'ما اسم هجوم غوكو المميز؟' }, opts: { en: ['Rasengan', 'Kamehameha', 'Hadouken', 'Spirit Bomb'], fr: ['Rasengan', 'Kamehameha', 'Hadouken', 'Boule d\'énergie'], ar: ['راسينغان', 'كاميهاميها', 'هادوكين', 'قنبلة الروح'] }, correct: 1, category: { en: 'Anime', fr: 'Anime', ar: 'أنمي' } },
  { q: { en: 'Who is the captain of the Survey Corps in Attack on Titan?', fr: 'Qui est le capitaine du Bataillon d\'exploration?', ar: 'من هو قائد فيلق الاستكشاف في هجوم العمالقة؟' }, opts: { en: ['Erwin', 'Levi', 'Eren', 'Mikasa'], fr: ['Erwin', 'Levi', 'Eren', 'Mikasa'], ar: ['إروين', 'ليفاي', 'إيرين', 'ميكاسا'] }, correct: 1, category: { en: 'Anime', fr: 'Anime', ar: 'أنمي' } },

  // ===== MOVIES =====
  { q: { en: 'Who directed Inception?', fr: 'Qui a réalisé Inception?', ar: 'من أخرج فيلم Inception؟' }, opts: { en: ['Spielberg', 'Nolan', 'Cameron', 'Tarantino'], fr: ['Spielberg', 'Nolan', 'Cameron', 'Tarantino'], ar: ['سبيلبرغ', 'نولان', 'كاميرون', 'تارانتينو'] }, correct: 1, category: { en: 'Movies', fr: 'Films', ar: 'أفلام' } },
  { q: { en: 'Which movie won Best Picture 2020?', fr: 'Quel film a gagné en 2020?', ar: 'أي فيلم فاز بجائزة أفضل فيلم 2020؟' }, opts: { en: ['1917', 'Joker', 'Parasite', 'Once Upon'], fr: ['1917', 'Joker', 'Parasite', 'Once Upon'], ar: ['1917', 'جوكر', 'باراسايت', 'Once Upon'] }, correct: 2, category: { en: 'Movies', fr: 'Films', ar: 'أفلام' } },
  { q: { en: 'Who played Iron Man in the MCU?', fr: 'Qui a joué Iron Man?', ar: 'من لعب دور آيرون مان في MCU؟' }, opts: { en: ['Chris Evans', 'Robert Downey Jr', 'Chris Hemsworth', 'Mark Ruffalo'], fr: ['Chris Evans', 'Robert Downey Jr', 'Chris Hemsworth', 'Mark Ruffalo'], ar: ['كريس إيفانز', 'روبرت داوني جونيور', 'كريس هيمسوورث', 'مارك روفالو'] }, correct: 1, category: { en: 'Movies', fr: 'Films', ar: 'أفلام' } },
  { q: { en: 'What year was The Matrix released?', fr: 'En quelle année Matrix est-il sorti?', ar: 'في أي سنة صدر فيلم ذا ماتريكس؟' }, opts: { en: ['1997', '1998', '1999', '2000'], fr: ['1997', '1998', '1999', '2000'], ar: ['1997', '1998', '1999', '2000'] }, correct: 2, category: { en: 'Movies', fr: 'Films', ar: 'أفلام' } },

  // ===== GEOGRAPHY & CAPITALS =====
  { q: { en: 'Capital of Morocco?', fr: 'Capitale du Maroc?', ar: 'عاصمة المغرب؟' }, opts: { en: ['Casablanca', 'Rabat', 'Marrakech', 'Fes'], fr: ['Casablanca', 'Rabat', 'Marrakech', 'Fès'], ar: ['الدار البيضاء', 'الرباط', 'مراكش', 'فاس'] }, correct: 1, category: { en: 'Geography', fr: 'Géographie', ar: 'جغرافيا' } },
  { q: { en: 'Capital of Japan?', fr: 'Capitale du Japon?', ar: 'عاصمة اليابان؟' }, opts: { en: ['Osaka', 'Kyoto', 'Tokyo', 'Hiroshima'], fr: ['Osaka', 'Kyoto', 'Tokyo', 'Hiroshima'], ar: ['أوساكا', 'كيوتو', 'طوكيو', 'هيروشيما'] }, correct: 2, category: { en: 'Geography', fr: 'Géographie', ar: 'جغرافيا' } },
  { q: { en: 'Capital of Germany?', fr: 'Capitale de l\'Allemagne?', ar: 'عاصمة ألمانيا؟' }, opts: { en: ['Munich', 'Hamburg', 'Berlin', 'Frankfurt'], fr: ['Munich', 'Hambourg', 'Berlin', 'Francfort'], ar: ['ميونخ', 'هامبورغ', 'برلين', 'فرانكفورت'] }, correct: 2, category: { en: 'Geography', fr: 'Géographie', ar: 'جغرافيا' } },
  { q: { en: 'Capital of Spain?', fr: 'Capitale de l\'Espagne?', ar: 'عاصمة إسبانيا؟' }, opts: { en: ['Barcelona', 'Madrid', 'Valencia', 'Seville'], fr: ['Barcelone', 'Madrid', 'Valence', 'Séville'], ar: ['برشلونة', 'مدريد', 'فالنسيا', 'إشبيلية'] }, correct: 1, category: { en: 'Geography', fr: 'Géographie', ar: 'جغرافيا' } },
  { q: { en: 'Capital of Saudi Arabia?', fr: 'Capitale de l\'Arabie Saoudite?', ar: 'عاصمة السعودية؟' }, opts: { en: ['Jeddah', 'Riyadh', 'Mecca', 'Medina'], fr: ['Djeddah', 'Riyad', 'La Mecque', 'Médine'], ar: ['جدة', 'الرياض', 'مكة', 'المدينة'] }, correct: 1, category: { en: 'Geography', fr: 'Géographie', ar: 'جغرافيا' } },

  // ===== TECHNOLOGY =====
  { q: { en: 'What does CPU stand for?', fr: 'Que signifie CPU?', ar: 'ماذا يعني CPU؟' }, opts: { en: ['Central Processing Unit', 'Computer Personal Unit', 'Central Program', 'Core Processing'], fr: ['Unité Centrale', 'Unité Personnelle', 'Programme Central', 'Traitement Core'], ar: ['وحدة المعالجة المركزية', 'وحدة الحاسوب الشخصية', 'البرنامج المركزي', 'معالج النواة'] }, correct: 0, category: { en: 'Technology', fr: 'Technologie', ar: 'تكنولوجيا' } },
  { q: { en: 'Who founded Apple?', fr: 'Qui a fondé Apple?', ar: 'من أسس شركة أبل؟' }, opts: { en: ['Bill Gates', 'Steve Jobs', 'Elon Musk', 'Mark Zuckerberg'], fr: ['Bill Gates', 'Steve Jobs', 'Elon Musk', 'Mark Zuckerberg'], ar: ['بيل غيتس', 'ستيف جوبز', 'إيلون ماسك', 'مارك زوكربيرغ'] }, correct: 1, category: { en: 'Technology', fr: 'Technologie', ar: 'تكنولوجيا' } },

  // ===== SCIENCE =====
  { q: { en: 'Speed of light?', fr: 'Vitesse de la lumière?', ar: 'سرعة الضوء؟' }, opts: { en: ['300,000 km/s', '150,000 km/s', '500,000 km/s', '100,000 km/s'], fr: ['300 000 km/s', '150 000 km/s', '500 000 km/s', '100 000 km/s'], ar: ['300,000 كم/ث', '150,000 كم/ث', '500,000 كم/ث', '100,000 كم/ث'] }, correct: 0, category: { en: 'Science', fr: 'Science', ar: 'علوم' } },
  { q: { en: 'How many planets in solar system?', fr: 'Combien de planètes dans le système solaire?', ar: 'كم عدد الكواكب في النظام الشمسي؟' }, opts: { en: ['7', '8', '9', '10'], fr: ['7', '8', '9', '10'], ar: ['7', '8', '9', '10'] }, correct: 1, category: { en: 'Science', fr: 'Science', ar: 'علوم' } },

  // ===== HISTORY =====
  { q: { en: 'When did WW2 end?', fr: 'Quand la 2e GM s\'est terminée?', ar: 'متى انتهت الحرب العالمية الثانية؟' }, opts: { en: ['1943', '1944', '1945', '1946'], fr: ['1943', '1944', '1945', '1946'], ar: ['1943', '1944', '1945', '1946'] }, correct: 2, category: { en: 'History', fr: 'Histoire', ar: 'تاريخ' } },

  // ===== GAMING =====
  { q: { en: 'Year Minecraft released?', fr: 'Année de sortie de Minecraft?', ar: 'سنة إصدار ماينكرافت؟' }, opts: { en: ['2009', '2010', '2011', '2012'], fr: ['2009', '2010', '2011', '2012'], ar: ['2009', '2010', '2011', '2012'] }, correct: 2, category: { en: 'Gaming', fr: 'Jeux', ar: 'ألعاب' } },
  { q: { en: 'Who is Mario\'s brother?', fr: 'Qui est le frère de Mario?', ar: 'من هو أخو ماريو؟' }, opts: { en: ['Wario', 'Luigi', 'Yoshi', 'Toad'], fr: ['Wario', 'Luigi', 'Yoshi', 'Toad'], ar: ['واريو', 'لويجي', 'يوشي', 'تود'] }, correct: 1, category: { en: 'Gaming', fr: 'Jeux', ar: 'ألعاب' } },

  // ===== SPORTS =====
  { q: { en: 'Players in football team?', fr: 'Joueurs dans une équipe?', ar: 'عدد اللاعبين في فريق كرة القدم؟' }, opts: { en: ['9', '10', '11', '12'], fr: ['9', '10', '11', '12'], ar: ['9', '10', '11', '12'] }, correct: 2, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  { q: { en: 'Olympic rings count?', fr: 'Nombre d\'anneaux olympiques?', ar: 'عدد حلقات الأولمبياد؟' }, opts: { en: ['4', '5', '6', '7'], fr: ['4', '5', '6', '7'], ar: ['4', '5', '6', '7'] }, correct: 1, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  { q: { en: 'Messi nationality?', fr: 'Nationalité de Messi?', ar: 'جنسية ميسي؟' }, opts: { en: ['Brazil', 'Argentina', 'Spain', 'Portugal'], fr: ['Brésil', 'Argentine', 'Espagne', 'Portugal'], ar: ['البرازيل', 'الأرجنتين', 'إسبانيا', 'البرتغال'] }, correct: 1, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  { q: { en: 'Which country hosted 2022 World Cup?', fr: 'Quel pays a accueilli la Coupe du monde 2022?', ar: 'أي بلد استضاف كأس العالم 2022؟' }, opts: { en: ['Russia', 'Brazil', 'Qatar', 'UAE'], fr: ['Russie', 'Brésil', 'Qatar', 'Émirats'], ar: ['روسيا', 'البرازيل', 'قطر', 'الإمارات'] }, correct: 2, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  { q: { en: 'Ronaldo first club?', fr: 'Premier club de Ronaldo?', ar: 'أول نادي لرونالدو؟' }, opts: { en: ['Real Madrid', 'Manchester United', 'Sporting CP', 'Juventus'], fr: ['Real Madrid', 'Manchester United', 'Sporting CP', 'Juventus'], ar: ['ريال مدريد', 'مانشستر يونايتد', 'سبورتينغ', 'يوفنتوس'] }, correct: 2, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  
  // ===== NEW BOYS CONTENT - Personality & Lifestyle =====
  { q: { en: 'What type of guy are you?', fr: 'Quel type de gars es-tu?', ar: 'أي نوع من الرجال أنت؟' }, opts: { en: ["Leader", "Thinker", "Adventurer", "Loyal Friend"], fr: ["Leader", "Penseur", "Aventurier", "Ami loyal"], ar: ["قائد", "مفكر", "مغامر", "صديق مخلص"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'What motivates you the most?', fr: 'Qu\'est-ce qui te motive le plus?', ar: 'ما الذي يحفزك أكثر؟' }, opts: { en: ["Success", "Family", "Adventure", "Knowledge"], fr: ["Succès", "Famille", "Aventure", "Savoir"], ar: ["النجاح", "العائلة", "المغامرة", "المعرفة"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'Are you Sigma, Alpha, or Beta?', fr: 'Es-tu Sigma, Alpha ou Beta?', ar: 'هل أنت سيجما، ألفا، أم بيتا؟' }, opts: { en: ["Sigma", "Alpha", "Beta", "None"], fr: ["Sigma", "Alpha", "Beta", "Aucun"], ar: ["سيجما", "ألفا", "بيتا", "لا شيء"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'What is your real personality?', fr: 'Quelle est ta vraie personnalité?', ar: 'ما هي شخصيتك الحقيقية؟' }, opts: { en: ["Optimistic", "Pessimistic", "Realistic", "Idealistic"], fr: ["Optimiste", "Pessimiste", "Réaliste", "Idéaliste"], ar: ["متفائل", "متشائم", "واقعي", "مثالي"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'What is your hidden strength?', fr: 'Quelle est ta force cachée?', ar: 'ما هي قوتك الخفية؟' }, opts: { en: ["Patience", "Creativity", "Courage", "Empathy"], fr: ["Patience", "Créativité", "Courage", "Empathie"], ar: ["الصبر", "الإبداع", "الشجاعة", "التعاطف"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'Are you introvert or extrovert?', fr: 'Es-tu introverti ou extraverti?', ar: 'هل أنت منطوي أم منفتح؟' }, opts: { en: ["Introvert", "Extrovert", "Ambivert", "Depends on mood"], fr: ["Introverti", "Extraverti", "Ambivert", "Ça dépend"], ar: ["منطوي", "منفتح", "وسطي", "يعتمد على المزاج"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'What is your life energy level?', fr: 'Quel est ton niveau d\'énergie?', ar: 'ما هو مستوى طاقتك؟' }, opts: { en: ["High", "Medium", "Low", "Varies"], fr: ["Élevé", "Moyen", "Faible", "Variable"], ar: ["عالي", "متوسط", "منخفض", "متغير"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'Are you more emotional or logical?', fr: 'Es-tu plus émotionnel ou logique?', ar: 'هل أنت عاطفي أم منطقي أكثر؟' }, opts: { en: ["Emotional", "Logical", "Balanced", "Depends on situation"], fr: ["Émotionnel", "Logique", "Équilibré", "Ça dépend"], ar: ["عاطفي", "منطقي", "متوازن", "يعتمد على الموقف"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'What is your mindset type?', fr: 'Quel est ton type d\'état d\'esprit?', ar: 'ما هو نوع عقليتك؟' }, opts: { en: ["Growth", "Fixed", "Creative", "Analytical"], fr: ["Croissance", "Fixe", "Créatif", "Analytique"], ar: ["نمو", "ثابت", "إبداعي", "تحليلي"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'How confident are you?', fr: 'Quelle est ta confiance en toi?', ar: 'ما مدى ثقتك بنفسك؟' }, opts: { en: ["Very confident", "Somewhat confident", "Not confident", "Unsure"], fr: ["Très confiant", "Assez confiant", "Peu confiant", "Incertain"], ar: ["واثق جداً", "واثق إلى حد ما", "غير واثق", "غير متأكد"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },

  // ===== NEW BOYS CONTENT - Sports & Fitness =====
  { q: { en: 'Which sport fits your personality?', fr: 'Quel sport te correspond?', ar: 'أي رياضة تناسب شخصيتك؟' }, opts: { en: ["Football", "Basketball", "Swimming", "Martial Arts"], fr: ["Football", "Basket", "Natation", "Arts martiaux"], ar: ["كرة القدم", "كرة السلة", "السباحة", "فنون قتالية"] }, correct: 0, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  { q: { en: 'Which legendary player are you?', fr: 'Quel joueur de légende es-tu?', ar: 'أي لاعب أسطوري أنت؟' }, opts: { en: ["Messi", "Ronaldo", "Neymar", "Mbappe"], fr: ["Messi", "Ronaldo", "Neymar", "Mbappe"], ar: ["ميسي", "رونالدو", "نيمار", "مبابي"] }, correct: 0, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  { q: { en: 'Are you a natural athlete?', fr: 'Es-tu un athlète né?', ar: 'هل أنت رياضي بالفطرة؟' }, opts: { en: ["Yes", "No", "Sometimes", "Not sure"], fr: ["Oui", "Non", "Parfois", "Pas sûr"], ar: ["نعم", "لا", "أحياناً", "لست متأكداً"] }, correct: 0, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  { q: { en: 'What is your football IQ level?', fr: 'Quel est ton QI footballistique?', ar: 'ما هو مستوى ذكائك الكروي؟' }, opts: { en: ["High", "Medium", "Low", "Beginner"], fr: ["Élevé", "Moyen", "Faible", "Débutant"], ar: ["عالي", "متوسط", "منخفض", "مبتدئ"] }, correct: 0, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  { q: { en: 'Are you built for gym or calisthenics?', fr: 'Es-tu fait pour la gym ou la calisthénie?', ar: 'هل أنت مناسب للجيم أم تمارين وزن الجسم؟' }, opts: { en: ["Gym", "Calisthenics", "Both", "Neither"], fr: ["Gym", "Calisthénie", "Les deux", "Aucun"], ar: ["جيم", "تمارين وزن الجسم", "كلاهما", "لا شيء"] }, correct: 0, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  { q: { en: 'What is your fitness discipline level?', fr: 'Quel est ton niveau de discipline sportive?', ar: 'ما هو مستوى انضباطك الرياضي؟' }, opts: { en: ["High", "Medium", "Low", "Inconsistent"], fr: ["Élevé", "Moyen", "Faible", "Inconstant"], ar: ["عالي", "متوسط", "منخفض", "غير منتظم"] }, correct: 0, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  { q: { en: 'Which position fits you in football?', fr: 'Quelle position te convient au football?', ar: 'أي مركز يناسبك في كرة القدم؟' }, opts: { en: ["Forward", "Midfielder", "Defender", "Goalkeeper"], fr: ["Attaquant", "Milieu", "Défenseur", "Gardien"], ar: ["مهاجم", "وسط", "مدافع", "حارس مرمى"] }, correct: 0, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  { q: { en: 'Are you fast, strong, or technical?', fr: 'Es-tu rapide, fort ou technique?', ar: 'هل أنت سريع، قوي، أم تقني؟' }, opts: { en: ["Fast", "Strong", "Technical", "All"], fr: ["Rapide", "Fort", "Technique", "Tout"], ar: ["سريع", "قوي", "تقني", "كل شيء"] }, correct: 0, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  { q: { en: 'What sport should you master?', fr: 'Quel sport devrais-tu maîtriser?', ar: 'أي رياضة يجب أن تتقنها؟' }, opts: { en: ["Football", "Tennis", "Boxing", "Skateboarding"], fr: ["Football", "Tennis", "Boxe", "Skateboard"], ar: ["كرة القدم", "التنس", "الملاكمة", "التزلج"] }, correct: 0, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },
  { q: { en: 'What is your competitive level?', fr: 'Quel est ton niveau de compétitivité?', ar: 'ما هو مستوى تنافسيتك؟' }, opts: { en: ["Very Competitive", "Somewhat Competitive", "Not Competitive", "Casual"], fr: ["Très compétitif", "Assez compétitif", "Peu compétitif", "Loisir"], ar: ["تنافسي جداً", "تنافسي إلى حد ما", "غير تنافسي", "عادي"] }, correct: 0, category: { en: 'Sport', fr: 'Sport', ar: 'رياضة' } },

  // ===== NEW BOYS CONTENT - Movies, Anime & Gaming =====
  { q: { en: 'Which anime character are you?', fr: 'Quel personnage d\'anime es-tu?', ar: 'أي شخصية أنمي أنت؟' }, opts: { en: ["Naruto", "Luffy", "Goku", "Ichigo"], fr: ["Naruto", "Luffy", "Goku", "Ichigo"], ar: ["ناروتو", "لوفي", "غوكو", "إيتشيغو"] }, correct: 0, category: { en: 'Anime', fr: 'Anime', ar: 'أنمي' } },
  { q: { en: 'Are you more Naruto, Luffy, or Goku?', fr: 'Es-tu plus Naruto, Luffy ou Goku?', ar: 'هل أنت أشبه بناروتو، لوفي، أم غوكو؟' }, opts: { en: ["Naruto", "Luffy", "Goku", "None"], fr: ["Naruto", "Luffy", "Goku", "Aucun"], ar: ["ناروتو", "لوفي", "غوكو", "لا شيء"] }, correct: 0, category: { en: 'Anime', fr: 'Anime', ar: 'أنمي' } },
  { q: { en: 'What gaming style fits you?', fr: 'Quel style de jeu te convient?', ar: 'أي أسلوب ألعاب يناسبك؟' }, opts: { en: ["Strategist", "Aggressive", "Support", "Casual"], fr: ["Stratège", "Agressif", "Support", "Casual"], ar: ["استراتيجي", "عدواني", "داعم", "عادي"] }, correct: 0, category: { en: 'Gaming', fr: 'Jeux', ar: 'ألعاب' } },
  { q: { en: 'What video game character matches you?', fr: 'Quel personnage de jeu vidéo te correspond?', ar: 'أي شخصية ألعاب فيديو تشبهك؟' }, opts: { en: ["Mario", "Link", "Master Chief", "Kratos"], fr: ["Mario", "Link", "Master Chief", "Kratos"], ar: ["ماريو", "لينك", "ماستر شيف", "كراتوس"] }, correct: 0, category: { en: 'Gaming', fr: 'Jeux', ar: 'ألعاب' } },
  { q: { en: 'Which movie hero represents you?', fr: 'Quel héros de film te représente?', ar: 'أي بطل أفلام يمثلك؟' }, opts: { en: ["Iron Man", "Batman", "Spider-Man", "Captain America"], fr: ["Iron Man", "Batman", "Spider-Man", "Captain America"], ar: ["الرجل الحديدي", "باتمان", "الرجل العنكبوت", "كابتن أمريكا"] }, correct: 0, category: { en: 'Movies', fr: 'Films', ar: 'أفلام' } },
  { q: { en: 'Are you a strategist or fighter?', fr: 'Es-tu stratège ou combattant?', ar: 'هل أنت استراتيجي أم مقاتل؟' }, opts: { en: ["Strategist", "Fighter", "Both", "Neither"], fr: ["Stratège", "Combattant", "Les deux", "Aucun"], ar: ["استراتيجي", "مقاتل", "كلاهما", "لا شيء"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'What is your gamer personality?', fr: 'Quelle est ta personnalité de joueur?', ar: 'ما هي شخصيتك كلاعب؟' }, opts: { en: ["Casual", "Competitive", "Streamer", "Explorer"], fr: ["Casual", "Compétitif", "Streamer", "Explorateur"], ar: ["عادي", "تنافسي", "بث مباشر", "مستكشف"] }, correct: 0, category: { en: 'Gaming', fr: 'Jeux', ar: 'ألعاب' } },
  { q: { en: 'What anime arc describes your life?', fr: 'Quel arc d\'anime décrit ta vie?', ar: 'أي قوس أنمي يصف حياتك؟' }, opts: { en: ["Chunin Exam", "Marineford", "Frieza Saga", "Hunter Exam"], fr: ["Examen Chunin", "Marineford", "Saga Frieza", "Examen des Chasseurs"], ar: ["امتحان التشونين", "مارينفورد", "ملحمة فريزا", "امتحان الصيادين"] }, correct: 0, category: { en: 'Anime', fr: 'Anime', ar: 'أنمي' } },
  { q: { en: 'Which villain are you?', fr: 'Quel méchant es-tu?', ar: 'أي شرير أنت؟' }, opts: { en: ["Joker", "Frieza", "Dio", "Light Yagami"], fr: ["Joker", "Frieza", "Dio", "Light Yagami"], ar: ["الجوكر", "فريزا", "ديو", "لايت ياغامي"] }, correct: 0, category: { en: 'Movies', fr: 'Films', ar: 'أفلام' } },
  { q: { en: 'What is your power level?', fr: 'Quel est ton niveau de puissance?', ar: 'ما هو مستوى قوتك؟' }, opts: { en: ["Over 9000", "Average", "Below Average", "Unknown"], fr: ["Plus de 9000", "Moyen", "En dessous", "Inconnu"], ar: ["أكثر من 9000", "متوسط", "أقل من المتوسط", "مجهول"] }, correct: 0, category: { en: 'Anime', fr: 'Anime', ar: 'أنمي' } },

  // ===== NEW BOYS CONTENT - Future & Ambition =====
  { q: { en: 'What career fits you best?', fr: 'Quelle carrière te convient?', ar: 'أي مهنة تناسبك؟' }, opts: { en: ["Entrepreneur", "Engineer", "Artist", "Scientist"], fr: ["Entrepreneur", "Ingénieur", "Artiste", "Scientifique"], ar: ["ريادي", "مهندس", "فنان", "عالم"] }, correct: 0, category: { en: 'Career', fr: 'Carrière', ar: 'مسار مهني' } },
  { q: { en: 'Are you entrepreneurial or traditional?', fr: 'Es-tu entrepreneurial ou traditionnel?', ar: 'هل أنت ريادي أم تقليدي؟' }, opts: { en: ["Entrepreneurial", "Traditional", "Hybrid", "Undecided"], fr: ["Entrepreneurial", "Traditionnel", "Hybride", "Indécis"], ar: ["ريادي", "تقليدي", "هجين", "غير محدد"] }, correct: 0, category: { en: 'Career', fr: 'Carrière', ar: 'مسار مهني' } },
  { q: { en: 'What is your financial mindset?', fr: 'Quelle est ta mentalité financière?', ar: 'ما هي عقلية المال لديك؟' }, opts: { en: ["Saver", "Spender", "Investor", "Avoider"], fr: ["Épargnant", "Dépensier", "Investisseur", "Évitant"], ar: ["مدخر", "مصرف", "مستثمر", "متجنب"] }, correct: 0, category: { en: 'Career', fr: 'Carrière', ar: 'مسار مهني' } },
  { q: { en: 'How ambitious are you really?', fr: 'À quel point es-tu ambitieux?', ar: 'ما مدى طموحك حقاً؟' }, opts: { en: ["Very", "Somewhat", "Not much", "Unsure"], fr: ["Très", "Assez", "Pas beaucoup", "Incertain"], ar: ["كثيراً", "إلى حد ما", "قليلاً", "غير متأكد"] }, correct: 0, category: { en: 'Career', fr: 'Carrière', ar: 'مسار مهني' } },
  { q: { en: 'Are you a leader or follower?', fr: 'Es-tu leader ou suiveur?', ar: 'هل أنت قائد أم تابع؟' }, opts: { en: ["Leader", "Follower", "Both", "Neither"], fr: ["Leader", "Suiveur", "Les deux", "Aucun"], ar: ["قائد", "تابع", "كلاهما", "لا شيء"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'What is your future lifestyle?', fr: 'Quel sera ton style de vie futur?', ar: 'ما هو أسلوب حياتك المستقبلي؟' }, opts: { en: ["Luxurious", "Simple", "Adventurous", "Balanced"], fr: ["Luxueux", "Simple", "Aventureux", "Équilibré"], ar: ["فاخر", "بسيط", "مغامر", "متوازن"] }, correct: 0, category: { en: 'Career', fr: 'Carrière', ar: 'مسار مهني' } },
  { q: { en: 'How disciplined are you?', fr: 'Quelle est ta discipline?', ar: 'ما مدى انضباطك؟' }, opts: { en: ["Highly Disciplined", "Somewhat Disciplined", "Undisciplined", "Inconsistent"], fr: ["Très discipliné", "Assez discipliné", "Indiscipliné", "Inconstant"], ar: ["منضبط جداً", "منضبط إلى حد ما", "غير منضبط", "غير منتظم"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'What is your long-term potential?', fr: 'Quel est ton potentiel à long terme?', ar: 'ما هي قدراتك طويلة المدى؟' }, opts: { en: ["High", "Medium", "Low", "Unknown"], fr: ["Élevé", "Moyen", "Faible", "Inconnu"], ar: ["عالي", "متوسط", "منخفض", "مجهول"] }, correct: 0, category: { en: 'Career', fr: 'Carrière', ar: 'مسار مهني' } },
  { q: { en: 'How smart are you really?', fr: 'À quel point es-tu intelligent?', ar: 'ما مدى ذكائك حقاً؟' }, opts: { en: ["Very Smart", "Average", "Below Average", "Don't Know"], fr: ["Très intelligent", "Moyen", "En dessous", "Je ne sais pas"], ar: ["ذكي جداً", "متوسط", "أقل من المتوسط", "لا أعرف"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'What is your success path?', fr: 'Quel est ton chemin vers le succès?', ar: 'ما هو طريقك للنجاح؟' }, opts: { en: ["Hard Work", "Luck", "Connections", "Talent"], fr: ["Travail dur", "Chance", "Relations", "Talent"], ar: ["العمل الجاد", "الحظ", "العلاقات", "الموهبة"] }, correct: 0, category: { en: 'Career', fr: 'Carrière', ar: 'مسار مهني' } },

  // ===== NEW BOYS CONTENT - Relationships =====
  { q: { en: 'What type of boyfriend are you?', fr: 'Quel genre de petit ami es-tu?', ar: 'أي نوع من الأصدقاء أنت؟' }, opts: { en: ["Romantic", "Funny", "Loyal", "Protective"], fr: ["Romantique", "Drôle", "Loyal", "Protecteur"], ar: ["رومانسي", "مضحك", "مخلص", "حامي"] }, correct: 0, category: { en: 'Relationships', fr: 'Relations', ar: 'علاقات' } },
  { q: { en: 'Are you loyal or toxic?', fr: 'Es-tu loyal ou toxique?', ar: 'هل أنت مخلص أم سام؟' }, opts: { en: ["Loyal", "Toxic", "Sometimes Toxic", "Not Sure"], fr: ["Loyal", "Toxique", "Parfois toxique", "Pas sûr"], ar: ["مخلص", "سام", "سام أحياناً", "لست متأكداً"] }, correct: 0, category: { en: 'Relationships', fr: 'Relations', ar: 'علاقات' } },
  { q: { en: 'How romantic are you?', fr: 'À quel point es-tu romantique?', ar: 'ما مدى رومانسيتك؟' }, opts: { en: ["Very", "Somewhat", "Not romantic", "Unsure"], fr: ["Très", "Assez", "Peu romantique", "Incertain"], ar: ["كثيراً", "إلى حد ما", "غير رومانسي", "غير متأكد"] }, correct: 0, category: { en: 'Relationships', fr: 'Relations', ar: 'علاقات' } },
  { q: { en: 'What is your flirting style?', fr: 'Quel est ton style de flirt?', ar: 'ما هو أسلوب تدليعك؟' }, opts: { en: ["Playful", "Serious", "Shy", "Confident"], fr: ["Joueur", "Sérieux", "Timide", "Confiant"], ar: ["مرح", "جاد", "خجول", "واثق"] }, correct: 0, category: { en: 'Relationships', fr: 'Relations', ar: 'علاقات' } },
  { q: { en: 'Are you emotionally stable?', fr: 'Es-tu émotionnellement stable?', ar: 'هل أنت مستقر عاطفياً؟' }, opts: { en: ["Yes", "No", "Sometimes", "Not sure"], fr: ["Oui", "Non", "Parfois", "Pas sûr"], ar: ["نعم", "لا", "أحياناً", "لست متأكداً"] }, correct: 0, category: { en: 'Relationships', fr: 'Relations', ar: 'علاقات' } },
  { q: { en: 'Do you fall in love fast?', fr: 'Tombes-tu amoureux vite?', ar: 'هل تقع في الحب بسرعة؟' }, opts: { en: ["Yes", "No", "Sometimes", "Rarely"], fr: ["Oui", "Non", "Parfois", "Rarement"], ar: ["نعم", "لا", "أحياناً", "نادراً"] }, correct: 0, category: { en: 'Relationships', fr: 'Relations', ar: 'علاقات' } },
  { q: { en: 'What type of girl fits you?', fr: 'Quel type de fille te convient?', ar: 'أي نوع من الفتيات يناسبك؟' }, opts: { en: ["Kind", "Independent", "Funny", "Supportive"], fr: ["Gentille", "Indépendante", "Drôle", "Soutien"], ar: ["لطيفة", "مستقلة", "مضحكة", "داعمة"] }, correct: 0, category: { en: 'Relationships', fr: 'Relations', ar: 'علاقات' } },
  { q: { en: 'Are you ready for a relationship?', fr: 'Es-tu prêt pour une relation?', ar: 'هل أنت جاهز لعلاقة؟' }, opts: { en: ["Yes", "No", "Maybe", "Not sure"], fr: ["Oui", "Non", "Peut-être", "Pas sûr"], ar: ["نعم", "لا", "ربما", "لست متأكداً"] }, correct: 0, category: { en: 'Relationships', fr: 'Relations', ar: 'علاقات' } },
  { q: { en: 'What makes you attractive?', fr: 'Qu\'est-ce qui te rend attirant?', ar: 'ما الذي يجعلك جذاباً؟' }, opts: { en: ["Personality", "Looks", "Sense of Humor", "Confidence"], fr: ["Personnalité", "Apparence", "Sens de l\'humour", "Confiance"], ar: ["الشخصية", "المظهر", "حس الدعابة", "الثقة"] }, correct: 0, category: { en: 'Relationships', fr: 'Relations', ar: 'علاقات' } },
  { q: { en: 'Are you overprotective or chill?', fr: 'Es-tu surprotecteur ou détendu?', ar: 'هل أنت شديد الحماية أم مسترخي؟' }, opts: { en: ["Overprotective", "Chill", "Depends", "Neither"], fr: ["Surprotecteur", "Détendu", "Ça dépend", "Aucun"], ar: ["شديد الحماية", "مسترخي", "يعتمد", "لا شيء"] }, correct: 0, category: { en: 'Relationships', fr: 'Relations', ar: 'علاقات' } },
];

export const femaleQuestions = [
  // ===== PERSONALITY =====
  { q: { en: 'What personality type is creative and spontaneous?', fr: 'Quel type est créatif et spontané?', ar: 'أي نوع شخصية إبداعي وعفوي؟' }, opts: { en: ['INTJ', 'ENFP', 'ISTJ', 'ESTP'], fr: ['INTJ', 'ENFP', 'ISTJ', 'ESTP'], ar: ['INTJ', 'ENFP', 'ISTJ', 'ESTP'] }, correct: 1, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: 'Introvert vs Extrovert?', fr: 'Introverti vs Extraverti?', ar: 'منطوي مقابل منفتح؟' }, opts: { en: ['Energy from inside', 'Energy from outside', 'Both', 'Neither'], fr: ['Énergie intérieure', 'Énergie extérieure', 'Les deux', 'Aucun'], ar: ['طاقة من الداخل', 'طاقة من الخارج', 'كلاهما', 'لا شيء'] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },

  // ===== LOVE =====
  { q: { en: 'Love language: Acts of service?', fr: 'Langage d\'amour: Services?', ar: 'لغة الحب: أفعال الخدمة؟' }, opts: { en: ['Doing things', 'Words', 'Gifts', 'Touch'], fr: ['Faire des choses', 'Mots', 'Cadeaux', 'Contact'], ar: ['فعل الأشياء', 'الكلمات', 'الهدايا', 'اللمس'] }, correct: 0, category: { en: 'Love', fr: 'Amour', ar: 'حب' } },
  { q: { en: 'Best first date idea?', fr: 'Meilleure idée de premier rendez-vous?', ar: 'أفضل فكرة للموعد الأول؟' }, opts: { en: ['Coffee', 'Movies', 'Walk', 'Dinner'], fr: ['Café', 'Cinéma', 'Promenade', 'Dîner'], ar: ['قهوة', 'سينما', 'مشي', 'عشاء'] }, correct: 0, category: { en: 'Love', fr: 'Amour', ar: 'حب' } },

  // ===== FASHION =====
  { q: { en: 'What is haute couture?', fr: 'Qu\'est-ce que la haute couture?', ar: 'ما هي الأزياء الراقية؟' }, opts: { en: ['High fashion', 'Casual wear', 'Sportswear', 'Vintage'], fr: ['Haute mode', 'Décontracté', 'Sportif', 'Vintage'], ar: ['الموضة الراقية', 'ملابس عادية', 'ملابس رياضية', 'قديم'] }, correct: 0, category: { en: 'Fashion', fr: 'Mode', ar: 'موضة' } },
  { q: { en: 'Little black dress icon?', fr: 'Icône de la petite robe noire?', ar: 'أيقونة الفستان الأسود الصغير؟' }, opts: { en: ['Chanel', 'Dior', 'Prada', 'Gucci'], fr: ['Chanel', 'Dior', 'Prada', 'Gucci'], ar: ['شانيل', 'ديور', 'برادا', 'غوتشي'] }, correct: 0, category: { en: 'Fashion', fr: 'Mode', ar: 'موضة' } },

  // ===== BEAUTY =====
  { q: { en: 'What is contouring?', fr: 'Qu\'est-ce que le contouring?', ar: 'ما هو الكونتور؟' }, opts: { en: ['Face shaping makeup', 'Lip color', 'Eye shadow', 'Nail art'], fr: ['Maquillage sculptant', 'Rouge à lèvres', 'Ombre à paupières', 'Nail art'], ar: ['مكياج لتشكيل الوجه', 'لون الشفاه', 'ظل العيون', 'فن الأظافر'] }, correct: 0, category: { en: 'Beauty', fr: 'Beauté', ar: 'جمال' } },
  { q: { en: 'SPF in skincare protects from?', fr: 'SPF protège de quoi?', ar: 'SPF في العناية بالبشرة يحمي من؟' }, opts: { en: ['Sun', 'Wind', 'Cold', 'Heat'], fr: ['Soleil', 'Vent', 'Froid', 'Chaleur'], ar: ['الشمس', 'الرياح', 'البرد', 'الحرارة'] }, correct: 0, category: { en: 'Beauty', fr: 'Beauté', ar: 'جمال' } },

  // ===== K-POP =====
  { q: { en: 'BTS stands for?', fr: 'BTS signifie?', ar: 'BTS تعني؟' }, opts: { en: ['Bangtan Sonyeondan', 'Best Time Songs', 'Big Time Stars', 'Beyond The Stars'], fr: ['Bangtan Sonyeondan', 'Best Time Songs', 'Big Time Stars', 'Beyond The Stars'], ar: ['بانغتان سونيوندان', 'أفضل وقت الأغاني', 'نجوم الوقت الكبير', 'ما وراء النجوم'] }, correct: 0, category: { en: 'K-pop', fr: 'K-pop', ar: 'كيه بوب' } },
  { q: { en: 'Blackpink member count?', fr: 'Nombre de membres Blackpink?', ar: 'عدد أعضاء بلاك بينك؟' }, opts: { en: ['3', '4', '5', '6'], fr: ['3', '4', '5', '6'], ar: ['3', '4', '5', '6'] }, correct: 1, category: { en: 'K-pop', fr: 'K-pop', ar: 'كيه بوب' } },

  // ===== DISNEY =====
  { q: { en: 'First Disney princess?', fr: 'Première princesse Disney?', ar: 'أول أميرة ديزني؟' }, opts: { en: ['Cinderella', 'Snow White', 'Aurora', 'Ariel'], fr: ['Cendrillon', 'Blanche-Neige', 'Aurore', 'Ariel'], ar: ['سندريلا', 'سنو وايت', 'أورورا', 'أريل'] }, correct: 1, category: { en: 'Disney', fr: 'Disney', ar: 'ديزني' } },
  { q: { en: 'Elsa\'s sister name?', fr: 'Nom de la sœur d\'Elsa?', ar: 'اسم أخت إلسا؟' }, opts: { en: ['Anna', 'Belle', 'Jasmine', 'Rapunzel'], fr: ['Anna', 'Belle', 'Jasmine', 'Raiponce'], ar: ['آنا', 'بيل', 'ياسمين', 'رابونزل'] }, correct: 0, category: { en: 'Disney', fr: 'Disney', ar: 'ديزني' } },

  // ===== FOOD & OTHERS =====
  { q: { en: 'Sushi originated in?', fr: 'Origine des sushis?', ar: 'أصل السوشي؟' }, opts: { en: ['China', 'Japan', 'Korea', 'Thailand'], fr: ['Chine', 'Japon', 'Corée', 'Thaïlande'], ar: ['الصين', 'اليابان', 'كوريا', 'تايلاند'] }, correct: 1, category: { en: 'Food', fr: 'Nourriture', ar: 'طعام' } },

  // ===== NEW GIRLS CONTENT - Personality & Aesthetic =====
  { q: { en: "What type of girl are you?", fr: "Quel type de fille es-tu?", ar: "أي نوع من الفتيات أنت؟" }, opts: { en: ["Creative", "Adventurous", "Shy", "Confident"], fr: ["Créative", "Aventureuse", "Timide", "Confiante"], ar: ["مبدعة", "مغامرة", "خجولة", "واثقة"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "What is your aesthetic?", fr: "Quelle est ton esthétique?", ar: "ما هو ذوقك الجمالي؟" }, opts: { en: ["Vintage", "Minimalist", "Boho", "Glam"], fr: ["Vintage", "Minimaliste", "Bohème", "Glamour"], ar: ["أنتيك", "بسيط", "بوهيمي", "جذاب"] }, correct: 0, category: { en: 'Fashion', fr: 'Mode', ar: 'موضة' } },
  { q: { en: "What is your love language?", fr: "Quel est ton langage d'amour?", ar: "ما هي لغة الحب الخاصة بك؟" }, opts: { en: ["Words of Affirmation", "Acts of Service", "Receiving Gifts", "Physical Touch", "Quality Time"], fr: ["Paroles valorisantes", "Actes de service", "Recevoir des cadeaux", "Contact physique", "Temps de qualité"], ar: ["كلمات التشجيع", "أفعال الخدمة", "تلقي الهدايا", "اللمس الجسدي", "الوقت النوعي"] }, correct: 0, category: { en: 'Love', fr: 'Amour', ar: 'حب' } },
  { q: { en: "Which flower matches your personality?", fr: "Quelle fleur correspond à ta personnalité?", ar: "أي زهرة تطابق شخصيتك؟" }, opts: { en: ["Rose", "Sunflower", "Lily", "Orchid"], fr: ["Rose", "Tournesol", "Lys", "Orchidée"], ar: ["وردة", "عباد الشمس", "زنبق", "أوركيد"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "What hairstyle fits you?", fr: "Quelle coiffure te va?", ar: "أي تسريحة تناسبك؟" }, opts: { en: ["Long and Wavy", "Short Bob", "Curly Afro", "Straight and Sleek"], fr: ["Long et ondulé", "Bob court", "Afro bouclé", "Lisse et brillant"], ar: ["طويل ومموج", "بوب قصير", "أفرو مجعد", "ناعم ومستقيم"] }, correct: 0, category: { en: 'Beauty', fr: 'Beauté', ar: 'جمال' } },
  { q: { en: "What color represents your soul?", fr: "Quelle couleur représente ton âme?", ar: "أي لون يمثل روحك؟" }, opts: { en: ["Blue", "Red", "Purple", "Green"], fr: ["Bleu", "Rouge", "Violet", "Vert"], ar: ["أزرق", "أحمر", "بنفسجي", "أخضر"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "What is your hidden personality?", fr: "Quelle est ta personnalité cachée?", ar: "ما هي شخصيتك الخفية؟" }, opts: { en: ["Introverted", "Optimistic", "Mysterious", "Energetic"], fr: ["Introverti", "Optimiste", "Mystérieux", "Énergique"], ar: ["منطوي", "متفائل", "غامض", "نشيط"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "How romantic are you?", fr: "À quel point es-tu romantique?", ar: "ما مدى رومانسيتك؟" }, opts: { en: ["Very Romantic", "Somewhat Romantic", "Not Romantic", "I Don't Know"], fr: ["Très romantique", "Assez romantique", "Pas romantique", "Je ne sais pas"], ar: ["رومانسي جداً", "رومانسي بعض الشيء", "غير رومانسي", "لا أعرف"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "What is your emotional type?", fr: "Quel est ton type émotionnel?", ar: "ما هو نوعك العاطفي؟" }, opts: { en: ["Sensitive", "Stable", "Moody", "Calm"], fr: ["Sensible", "Stable", "De mauvaise humeur", "Calme"], ar: ["حساس", "مستقر", "متقلب المزاج", "هادئ"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "Are you soft girl or baddie?", fr: "Es-tu soft girl ou baddie?", ar: "هل أنت فتاة ناعمة أم فتاة قوية؟" }, opts: { en: ["Soft Girl", "Baddie", "Both", "Neither"], fr: ["Soft Girl", "Baddie", "Les deux", "Aucun"], ar: ["فتاة ناعمة", "فتاة قوية", "كلاهما", "لا شيء"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },

  // ===== NEW GIRLS CONTENT - Fashion & Makeup =====
  { q: { en: "What makeup style suits you?", fr: "Quel maquillage te va?", ar: "أي مكياج يناسبك؟" }, opts: { en: ["Natural", "Glam", "Bold", "Minimal"], fr: ["Naturel", "Glamour", "Audacieux", "Minimal"], ar: ["طبيعي", "جذاب", "جريء", "بسيط"] }, correct: 0, category: { en: 'Beauty', fr: 'Beauté', ar: 'جمال' } },
  { q: { en: "What is your fashion style?", fr: "Quel est ton style vestimentaire?", ar: "ما هو أسلوبك في الملابس؟" }, opts: { en: ["Casual", "Chic", "Sporty", "Bohemian"], fr: ["Décontracté", "Chic", "Sportif", "Bohème"], ar: ["عادي", "أنيق", "رياضي", "بوهيمي"] }, correct: 0, category: { en: 'Fashion', fr: 'Mode', ar: 'موضة' } },
  { q: { en: "Which perfume describes you?", fr: "Quel parfum te décrit?", ar: "أي عطر يصفك؟" }, opts: { en: ["Floral", "Citrus", "Woody", "Fresh"], fr: ["Floral", "Citronné", "Boisé", "Fraîcheur"], ar: ["زهور", "حمضيات", "خشبي", "منعش"] }, correct: 0, category: { en: 'Beauty', fr: 'Beauté', ar: 'جمال' } },
  { q: { en: "What nail style matches your vibe?", fr: "Quel style d'ongles correspond à ton vibe?", ar: "أي أسلوب أظافر يناسب جوهرك؟" }, opts: { en: ["French Tips", "Matte", "Glitter", "Short & Natural"], fr: ["French Tips", "Mat", "Paillettes", "Court et naturel"], ar: ["فرنسي", "غير لامع", "لامع", "قصير وطبيعي"] }, correct: 0, category: { en: 'Beauty', fr: 'Beauté', ar: 'جمال' } },
  { q: { en: "Which outfit fits your mood?", fr: "Quelle tenue correspond à ton humeur?", ar: "أي زي يناسب مزاجك؟" }, opts: { en: ["Dress", "Jeans & T-shirt", "Athleisure", "Skirt & Blouse"], fr: ["Robe", "Jeans & T-shirt", "Athleisure", "Jupe & Chemisier"], ar: ["فستان", "جينز وتي شيرت", "رياضي", "تنورة وبلوزة"] }, correct: 0, category: { en: 'Fashion', fr: 'Mode', ar: 'موضة' } },
  { q: { en: "Which accessories fit your personality?", fr: "Quels accessoires correspondent à ta personnalité?", ar: "أي إكسسوارات تناسب شخصيتك؟" }, opts: { en: ["Statement Earrings", "Delicate Necklace", "Bracelets", "Rings"], fr: ["Boucles d'oreilles voyantes", "Collier délicat", "Bracelets", "Bagues"], ar: ["أقراط بارزة", "قلادة رقيقة", "أساور", "خواتم"] }, correct: 0, category: { en: 'Fashion', fr: 'Mode', ar: 'موضة' } },
  { q: { en: "Are you vintage, modern, or classy?", fr: "Es-tu vintage, moderne ou classe?", ar: "هل أنت أنتيك، عصري، أم أنيق؟" }, opts: { en: ["Vintage", "Modern", "Classy", "Eclectic"], fr: ["Vintage", "Moderne", "Classe", "Éclectique"], ar: ["أنتيك", "عصري", "أنيق", "متنوع"] }, correct: 0, category: { en: 'Fashion', fr: 'Mode', ar: 'موضة' } },
  { q: { en: "Which fashion era are you?", fr: "De quelle époque de mode es-tu?", ar: "من أي عصر موضة أنت؟" }, opts: { en: ["70s", "80s", "90s", "2000s"], fr: ["Années 70", "Années 80", "Années 90", "Années 2000"], ar: ["السبعينيات", "الثمانينيات", "التسعينيات", "الألفية"] }, correct: 0, category: { en: 'Fashion', fr: 'Mode', ar: 'موضة' } },

  // ===== NEW GIRLS CONTENT - Love & Relationships =====
  { q: { en: "What type of boyfriend fits you?", fr: "Quel type de petit ami te convient?", ar: "أي نوع من الأصدقاء يناسبك؟" }, opts: { en: ["Romantic", "Funny", "Loyal", "Adventurous"], fr: ["Romantique", "Drôle", "Loyal", "Aventureux"], ar: ["رومانسي", "مضحك", "مخلص", "مغامر"] }, correct: 0, category: { en: 'Love', fr: 'Amour', ar: 'حب' } },
  { q: { en: "Are you ready for a relationship?", fr: "Es-tu prête pour une relation?", ar: "هل أنت جاهزة لعلاقة؟" }, opts: { en: ["Yes", "No", "Maybe", "Not sure"], fr: ["Oui", "Non", "Peut-être", "Pas sûr"], ar: ["نعم", "لا", "ربما", "لست متأكدة"] }, correct: 0, category: { en: 'Love', fr: 'Amour', ar: 'حب' } },
  { q: { en: "What is your flirting style?", fr: "Quel est ton style de flirt?", ar: "ما هو أسلوب تدليعك؟" }, opts: { en: ["Playful", "Shy", "Confident", "Subtle"], fr: ["Joueur", "Timide", "Confiant", "Subtil"], ar: ["مرح", "خجول", "واثق", "دقيق"] }, correct: 0, category: { en: 'Love', fr: 'Amour', ar: 'حب' } },
  { q: { en: "How jealous are you?", fr: "À quel point es-tu jalouse?", ar: "ما مدى غيرتك؟" }, opts: { en: ["Very", "Sometimes", "Rarely", "Never"], fr: ["Très", "Parfois", "Rarement", "Jamais"], ar: ["كثيراً", "أحياناً", "نادراً", "أبداً"] }, correct: 0, category: { en: 'Love', fr: 'Amour', ar: 'حب' } },
  { q: { en: "Are you a loyal partner?", fr: "Es-tu une partenaire loyale?", ar: "هل أنت شريكة مخلصة؟" }, opts: { en: ["Yes", "Mostly", "Sometimes", "Not really"], fr: ["Oui", "Principalement", "Parfois", "Pas vraiment"], ar: ["نعم", "غالباً", "أحياناً", "ليس حقاً"] }, correct: 0, category: { en: 'Love', fr: 'Amour', ar: 'حب' } },
  { q: { en: "What type of friend are you?", fr: "Quel type d'amie es-tu?", ar: "أي نوع من الصديقات أنت؟" }, opts: { en: ["Supportive", "Funny", "Reliable", "Adventurous"], fr: ["Soutenante", "Drôle", "Fiable", "Aventureuse"], ar: ["داعمة", "مضحكة", "موثوقة", "مغامرة"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "Are you emotionally available?", fr: "Es-tu émotionnellement disponible?", ar: "هل أنت متاحة عاطفياً؟" }, opts: { en: ["Yes", "No", "Sometimes", "Not sure"], fr: ["Oui", "Non", "Parfois", "Pas sûr"], ar: ["نعم", "لا", "أحياناً", "لست متأكدة"] }, correct: 0, category: { en: 'Love', fr: 'Amour', ar: 'حب' } },

  // ===== NEW GIRLS CONTENT - Movies, Anime & Series =====
  { q: { en: "Which movie heroine are you?", fr: "Quelle héroïne de film es-tu?", ar: "أي بطلة أفلام أنت؟" }, opts: { en: ["Wonder Woman", "Hermione Granger", "Katniss Everdeen", "Black Widow"], fr: ["Wonder Woman", "Hermione Granger", "Katniss Everdeen", "Black Widow"], ar: ["المرأة المعجزة", "هيرميون جرانجر", "كاتنيس إيفردين", "الأرملة السوداء"] }, correct: 0, category: { en: 'Movies', fr: 'Films', ar: 'أفلام' } },
  { q: { en: "Which Disney princess are you?", fr: "Quelle princesse Disney es-tu?", ar: "أي أميرة ديزني أنت؟" }, opts: { en: ["Cinderella", "Belle", "Ariel", "Elsa"], fr: ["Cendrillon", "Belle", "Ariel", "Elsa"], ar: ["سندريلا", "بيل", "أريل", "إلسا"] }, correct: 0, category: { en: 'Disney', fr: 'Disney', ar: 'ديزني' } },
  { q: { en: "Which anime girl are you?", fr: "Quelle fille d'anime es-tu?", ar: "أي فتاة أنمي أنت؟" }, opts: { en: ["Sailor Moon", "Sakura", "Mikasa", "Nezuko"], fr: ["Sailor Moon", "Sakura", "Mikasa", "Nezuko"], ar: ["سيلور مون", "ساكورا", "ميكاسا", "نيزوكو"] }, correct: 0, category: { en: 'Anime', fr: 'Anime', ar: 'أنمي' } },
  { q: { en: "What K-Drama fits your life?", fr: "Quel K-Drama correspond à ta vie?", ar: "أي دراما كورية تناسب حياتك؟" }, opts: { en: ["Crash Landing On You", "Goblin", "Start-Up", "Itaewon Class"], fr: ["Crash Landing On You", "Goblin", "Start-Up", "Itaewon Class"], ar: ["هبوط اضطراري عليك", "العفريت", "ستارت أب", "صف إتايون"] }, correct: 0, category: { en: 'Movies', fr: 'Films', ar: 'أفلام' } },
  { q: { en: "Which series matches your vibe?", fr: "Quelle série correspond à ton vibe?", ar: "أي مسلسل يناسب جوهرك؟" }, opts: { en: ["Friends", "Stranger Things", "Euphoria", "Sex Education"], fr: ["Friends", "Stranger Things", "Euphoria", "Sex Education"], ar: ["أصدقاء", "أشياء غريبة", "النشوة", "تثقيف جنسي"] }, correct: 0, category: { en: 'Movies', fr: 'Films', ar: 'أفلام' } },
  { q: { en: "Are you Wednesday or Enid?", fr: "Es-tu Wednesday ou Enid?", ar: "هل أنت وينزداي أم إينيد؟" }, opts: { en: ["Wednesday", "Enid", "Both", "Neither"], fr: ["Wednesday", "Enid", "Les deux", "Aucun"], ar: ["وينزداي", "إينيد", "كلاهما", "لا شيء"] }, correct: 0, category: { en: 'Movies', fr: 'Films', ar: 'أفلام' } },
  { q: { en: "Which Studio Ghibli character are you?", fr: "Quel personnage de Studio Ghibli es-tu?", ar: "أي شخصية من استوديو جيبلي أنت؟" }, opts: { en: ["Chihiro", "Kiki", "Sophie", "San"], fr: ["Chihiro", "Kiki", "Sophie", "San"], ar: ["تشيهيرو", "كيكي", "صوفي", "سان"] }, correct: 0, category: { en: 'Movies', fr: 'Films', ar: 'أفلام' } },

  // ===== NEW GIRLS CONTENT - Music & Lifestyle =====
  { q: { en: "What music genre matches your soul?", fr: "Quel genre musical correspond à ton âme?", ar: "أي نوع موسيقى يطابق روحك؟" }, opts: { en: ["Pop", "Rock", "R&B", "Classical"], fr: ["Pop", "Rock", "R&B", "Classique"], ar: ["بوب", "روك", "آر أند بي", "كلاسيكي"] }, correct: 0, category: { en: 'Music', fr: 'Musique', ar: 'موسيقى' } },
  { q: { en: "Which artist represents your mood?", fr: "Quel artiste représente ton humeur?", ar: "أي فنان يمثل مزاجك؟" }, opts: { en: ["Taylor Swift", "Beyoncé", "Billie Eilish", "Adele"], fr: ["Taylor Swift", "Beyoncé", "Billie Eilish", "Adele"], ar: ["تايلور سويفت", "بيونسيه", "بيلي آيليش", "أديل"] }, correct: 0, category: { en: 'Music', fr: 'Musique', ar: 'موسيقى' } },
  { q: { en: "What is your daily vibe?", fr: "Quelle est ton ambiance quotidienne?", ar: "ما هو جوهرك اليومي؟" }, opts: { en: ["Energetic", "Calm", "Focused", "Creative"], fr: ["Énergique", "Calme", "Concentré", "Créatif"], ar: ["نشيط", "هادئ", "مركز", "خلاق"] }, correct: 0, category: { en: 'Lifestyle', fr: 'Mode de vie', ar: 'أسلوب حياة' } },
  { q: { en: "What is your weekend personality?", fr: "Quelle est ta personnalité de weekend?", ar: "ما هي شخصية عطلة نهاية الأسبوع لديك؟" }, opts: { en: ["Party Lover", "Homebody", "Explorer", "Relaxed"], fr: ["Fêtard", "Casanier", "Explorateur", "Détendu"], ar: ["محب للحفلات", "منزلي", "مستكشف", "مسترخي"] }, correct: 0, category: { en: 'Lifestyle', fr: 'Mode de vie', ar: 'أسلوب حياة' } },
  { q: { en: "Are you an introvert or extrovert?", fr: "Es-tu introvertie ou extravertie?", ar: "هل أنت منطوية أم منفتحة؟" }, opts: { en: ["Introvert", "Extrovert", "Ambivert", "Depends"], fr: ["Introverti", "Extraverti", "Ambivert", "Ça dépend"], ar: ["منطوية", "منفتحة", "وسطية", "يعتمد"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "What is your sleeping personality?", fr: "Quelle est ta personnalité de sommeil?", ar: "ما هي شخصية نومك؟" }, opts: { en: ["Early Bird", "Night Owl", "Light Sleeper", "Deep Sleeper"], fr: ["Lève-tôt", "Couche-tard", "Dormeur léger", "Dormeur profond"], ar: ["مبكرة", "بومة ليل", "نوم خفيف", "نوم عميق"] }, correct: 0, category: { en: 'Lifestyle', fr: 'Mode de vie', ar: 'أسلوب حياة' } },

  // ===== NEW GIRLS CONTENT - Fun & Social Media =====
  { q: { en: "How dramatic are you?", fr: "À quel point es-tu dramatique?", ar: "ما مدى دراميتك؟" }, opts: { en: ["Very", "Sometimes", "Rarely", "Not at all"], fr: ["Très", "Parfois", "Rarement", "Pas du tout"], ar: ["كثيراً", "أحياناً", "نادراً", "لا على الإطلاق"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "Are you a good secret keeper?", fr: "Es-tu bonne pour garder des secrets?", ar: "هل أنت جيدة في حفظ الأسرار؟" }, opts: { en: ["Yes", "No", "Sometimes", "Depends"], fr: ["Oui", "Non", "Parfois", "Ça dépend"], ar: ["نعم", "لا", "أحياناً", "يعتمد"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "Are you an angel or troublemaker?", fr: "Es-tu un ange ou une fauteuse de troubles?", ar: "هل أنت ملاك أم محبكة مشاكل؟" }, opts: { en: ["Angel", "Troublemaker", "Both", "Neither"], fr: ["Ange", "Fauteur de troubles", "Les deux", "Aucun"], ar: ["ملاك", "محبكة مشاكل", "كلاهما", "لا شيء"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "What is your mental age?", fr: "Quel est ton âge mental?", ar: "ما هو عمرك العقلي؟" }, opts: { en: ["Young", "Mature", "Wise", "Playful"], fr: ["Jeune", "Mature", "Sage", "Joueur"], ar: ["شاب", "ناضج", "حكيم", "مرح"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "What is your emotional intelligence?", fr: "Quelle est ton intelligence émotionnelle?", ar: "ما هي ذكاؤك العاطفي؟" }, opts: { en: ["High", "Average", "Low", "Unknown"], fr: ["Élevé", "Moyen", "Faible", "Inconnu"], ar: ["عالي", "متوسط", "منخفض", "مجهول"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "Are you lucky or unlucky?", fr: "Es-tu chanceuse ou malchanceuse?", ar: "هل أنت محظوظة أم غير محظوظة؟" }, opts: { en: ["Lucky", "Unlucky", "Sometimes lucky", "Don't believe in luck"], fr: ["Chanceuse", "Malchanceuse", "Parfois chanceuse", "Je ne crois pas à la chance"], ar: ["محظوظة", "غير محظوظة", "محظوظة أحياناً", "لا أؤمن بالحظ"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "What decade matches you?", fr: "Quelle décennie te correspond?", ar: "أي عقد يناسبك؟" }, opts: { en: ["60s", "70s", "80s", "90s"], fr: ["Années 60", "Années 70", "Années 80", "Années 90"], ar: ["الستينيات", "السبعينيات", "الثمانينيات", "التسعينيات"] }, correct: 0, category: { en: 'Lifestyle', fr: 'Mode de vie', ar: 'أسلوب حياة' } },
  { q: { en: "What is your spirit animal?", fr: "Quel est ton animal spirituel?", ar: "ما هو حيوانك الروحي؟" }, opts: { en: ["Wolf", "Cat", "Butterfly", "Dolphin"], fr: ["Loup", "Chat", "Papillon", "Dauphin"], ar: ["ذئب", "قط", "فراشة", "دلفين"] }, correct: 0, category: { en: 'Personality', fr: 'Personnalité', ar: 'شخصية' } },
  { q: { en: "What type of TikTok girl are you?", fr: "Quel type de fille TikTok es-tu?", ar: "أي نوع من فتيات تيك توك أنت؟" }, opts: { en: ["Dancer", "Comedian", "Fashionista", "Singer"], fr: ["Danseuse", "Comédienne", "Fashionista", "Chanteuse"], ar: ["راقصة", "ممثلة كوميدية", "خبيرة أزياء", "مغنية"] }, correct: 0, category: { en: 'Social Media', fr: 'Réseaux sociaux', ar: 'تواصل اجتماعي' } },
  { q: { en: "What is your Instagram vibe?", fr: "Quelle est ton ambiance Instagram?", ar: "ما هو جوهرك على انستغرام؟" }, opts: { en: ["Aesthetic", "Funny", "Inspirational", "Casual"], fr: ["Esthétique", "Drôle", "Inspirant", "Décontracté"], ar: ["جمالي", "مضحك", "ملهم", "عادي"] }, correct: 0, category: { en: 'Social Media', fr: 'Réseaux sociaux', ar: 'تواصل اجتماعي' } }
];

const MAX_LEVELS = 50;
const QUESTIONS_PER_LEVEL = 10;

// Helper to generate a level with either real questions or math filler
const generateLevel = (questionsSource, level, poolIndex) => {
  const difficulty = level <= 15 ? 'Easy' : level <= 30 ? 'Medium' : level <= 45 ? 'Hard' : 'Expert';
  
  const levelQuestions = [];
  
  // Try to grab up to 10 questions from source
  for (let i = 0; i < QUESTIONS_PER_LEVEL; i++) {
    const qIndex = (poolIndex + i) % questionsSource.length; 
    levelQuestions.push(questionsSource[qIndex]); 
  }
  
  return {
    difficulty,
    questions: levelQuestions
  };
};

export const getQuestions = (gender) => {
  const levels = {};
  const source = gender === 'female' ? femaleQuestions : maleQuestions;
  
  let poolIndex = 0;
  for (let level = 1; level <= MAX_LEVELS; level++) {
    levels[level] = generateLevel(source, level, poolIndex);
    poolIndex += QUESTIONS_PER_LEVEL;
  }
  return levels;
};
